apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api:lastest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
