services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
  db:
    image: postgres:16-alpine
    container_name: race-condition-db
    restart: no
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: race
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  pgdata: {}
